AWSTemplateFormatVersion: 2010-09-09
Resources:
  EmrDefaultRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: EMR_DefaultRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service: elasticmapreduce.amazonaws.com

  EmrEC2DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: EMR_EC2_DefaultRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service: ec2.amazonaws.com
